x-environment: &default-environment
  ENVIRONMENT_ACTIVE: local
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root_pass
  MONGO_INITDB_DATABASE: mongoose

services:
  backend:
    image: backend
    tty: true
    hostname: backend-koa
    build:
      context: ..
      dockerfile: .devcontainer/containers/workspace/Dockerfile
    environment:
      <<: *default-environment
    volumes:
      - ..:/workspace:consistent
      - /var/run/docker.sock:/var/run/docker.sock:consistent
      - ~/.aws:/home/dev-user/.aws:consistent
      - ../../auth-client-js:/workspace/.external/auth-client-js:consistent
      - ../../koa-inversify-framework:/workspace/.external/koa-inversify-framework:consistent
      - ../../node_modules/backend-koa/koa-inversify-framework:/workspace/.external/koa-inversify-framework/node_modules:consistent
      - ../../node_modules/backend-koa/auth-client-js:/workspace/.external/auth-client-js/node_modules:consistent
      - ../../auth-client-js:/workspace/.external/koa-inversify-framework/.external/auth-client-js:consistent
      - ../../node_modules/backend-koa/auth-client-js:/workspace/.external/koa-inversify-framework/.external/auth-client-js/node_modules:consistent
    ports:
      - 3000:3000
      - 9090:9090
      - 9464:9464
    networks:
      - dev-network
      - private-network
  mongo:
    image: mongo
    build:
      context: ..
      dockerfile: .devcontainer/containers/monogodb/Dockerfile
    environment:
      <<: *default-environment
    volumes:
      - ./containers/monogodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../.mongodata:/data/db:consistent
    ports:
      - 27017:27017
    networks:
      - dev-network
      - private-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686 # Jaeger UI
      - 14268:14268 # Jaeger collector HTTP
      - 4318:4318 # OTLP HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - dev-network
      - private-network

networks:
  private-network:
    driver: bridge
  dev-network:
    name: dev-network
    external: true
