x-environment: &default-environment
  ENVIRONMENT_ACTIVE: local
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root_pass
  MONGO_INITDB_DATABASE: mongoose

services:
  backend:
    image: backend
    tty: true
    build:
      context: ..
      dockerfile: .devcontainer/containers/workspace/Dockerfile
    environment:
      <<: *default-environment
    volumes:
      - ..:/workspace:consistent
      - /var/run/docker.sock:/var/run/docker.sock:consistent
    ports:
      - 3000:3000
    networks:
      - dev-network
      - private-network
  mongo:
    image: mongo
    build:
      context: ..
      dockerfile: .devcontainer/containers/monogodb/Dockerfile
    environment:
      <<: *default-environment
    volumes:
      - ./containers/monogodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../.mongodata:/data/db:consistent
    ports:
      - 27017:27017
    networks:
      - dev-network
      - private-network

networks:
  private-network:
    driver: bridge
  dev-network:
    name: dev-network
    external: true
